Multiple major changes.
- Adds script header with more information.
- Separates global variables in user variables and other variables.
- Sets default value for EXCLUDE_RE. (EXCLUDE_RE='sshfs|scp')
- Puts all sub jobs of the script into functions, improves variable scoping.
- Introduces parameter "-l|--list" which lists connections without asking
  for a connection id.
- Introduces "-h|--help" parameter.
- Writes ssh commands which are built via passed id (e.g. ">id: 3+2")
  also to history file.

diff --git a/ossh b/ossh
--- a/ossh
+++ b/ossh
@@ -1,142 +1,231 @@
-#!/bin/bash
-# Description: Show current ssh client connections and
+#!/bin/bash 
+# name:        ossh
+# description: List current ssh client connections and
 #              establish a further one if requested.
+# author:      vd@ghostshell.de
 set -e
+
+#-----------------------
+# Gloabl user variables
+#-----------------------
 
 HIST_FILE=~/.ossh_history
 MAX_HIST_LINES=6
 # Define optional exclude regex for ssh connections
 # which should not appear in the connection overview.
-EXCLUDE_RE=''
-INDEX=$1
+EXCLUDE_RE='sshfs|scp'
 
+#------------------------
+# Other global variables
+#------------------------
 
-# Check history file.
-if [[ ! -e $HIST_FILE ]]; then
-    hist_basedir=${HIST_FILE%/*}
-    [[ ! -e $hist_basedir ]] && mkdir -p $hist_basedir
-    touch $HIST_FILE
-fi
+PROG_NAME=${0##*/}
+ARGV=$@
+VALIDATION_PATTERN='^([0-9]{1,3}){0,1}([+-][0-9]{1,3}){0,1}$'
+AUTO_FLAG=false
+LIST_FLAG=false
 
-# Get current ssh connections.
-ssh_client_pids=$( lsof -n -iTCP -sTCP:ESTABLISHED | awk '/^ssh/{print $2}' )
+#-----------
+# Functions
+#-----------
 
-# Get current ssh command lines.
-if [[ -n $ssh_client_pids ]]; then
-    ps_list=$( ps -eo pid,args | grep '[s]sh' )
-    for pid in $ssh_client_pids; do
-        ssh_client_cmd="$( echo "$ps_list" \
-                            | awk -v pid=$pid '$1==pid{$1=""; sub(/^ /,""); print $0; exit}' )"
-        if [[ $ssh_client_cmd =~ ${EXCLUDE_RE:-^$} ]]; then
-            continue
+usage() {
+cat <<EOF
+Usage: $PROG_NAME [index] [-l|--list] [-a|--auto] [-h|--help]
+List or establish ssh connections.
+
+Options:
+ index      specify a numeric index to use from the overview, 
+            e.g. "2" or "+3" or "4+1" or "-2" or "3-1"
+ -l|--list  only list connections, do not a ask for a connection id
+            (mutually exclusive with "index".
+ -a|--auto  auto login if there is only one unique current connection
+ -h|--help  show this help
+
+EOF
+}
+
+parse_argv() {
+    for arg in $ARGV; do
+        if [[ $arg =~ ^(-h|--help)$ ]]; then
+            usage
+            exit
+        elif [[ $arg =~ ^(-a|--auto)$ ]]; then 
+            AUTO_FLAG=true
+        elif [[ $arg =~ ^(-l|--list)$ ]]; then 
+            LIST_FLAG=true
+        elif [[ $arg =~ ^(-la|-al)$ ]]; then
+            AUTO_FLAG=true
+            LIST_FLAG=true
+        elif [[ $arg =~ $VALIDATION_PATTERN ]]; then
+            INDEX=$arg
         else
-            conn_arr[ ${i:=0} ]="$ssh_client_cmd"
-            i=$(( $i + 1 ))
-        fi
+            echo "$arg: invalid parameter." >&2
+            echo "Try '$PROG_NAME -h' for more information." >&2
+            exit 1
+        fi  
     done
-fi
 
-# Exit if no current or history connections available.
-if [[ -z $conn_arr ]] && [[ ! -s $HIST_FILE ]]; then
-    echo "No current ssh connections and $HIST_FILE is empty." >&2
-    exit 1
-fi
-
-if [[ -s $HIST_FILE ]]; then
-    # Fill the history array.
-    while read line; do
-        hist_arr[ ${j:=0} ]="$line"
-        j=$(( $j + 1 ))
-    done < $HIST_FILE
-fi
-
-# Eliminate duplicate items in connection array.
-# Here the array expansion via wildcard and modified IFS are necessary.
-IFS=$'\n' conn_arr=( $( echo "${conn_arr[*]}" | sort -u ) )
-unset IFS
-# Some people want auto login if there is only one unique current
-# connection instead of printing the overview (dedicated to Alex).
-if [[ $INDEX =~ ^-a|--auto$ ]]; then
-    if [[ ${#conn_arr[@]} -eq 1 ]]; then
-        INDEX=0
-    else
-        # Either $2 is set or the variable gets an empty value.
-        INDEX="$2"
+    if $AUTO_FLAG && $LIST_FLAG; then
+        AUTO_FLAG=false
     fi
-fi
 
-# Continue here only if connection array is set.
-if [[ -n $conn_arr ]]; then
-    # Print current connections. 
-    for x in "${!conn_arr[@]}"; do
-        [[ -z $INDEX ]] && printf "[%02d] %s\n" $(( $x + 1 )) "${conn_arr[ $x ]}"
+    if $LIST_FLAG && [[ -n $INDEX ]]; then
+        echo "Specified parameters are mutually exclusive." >&2
+        echo "Try '$PROG_NAME -h' for more information." >&2
+        exit 1
+    fi
+}
+
+create_hist_file() {
+    local hist_basedir
+    if [[ ! -e $HIST_FILE ]]; then
+        hist_basedir=${HIST_FILE%/*}
+        [[ ! -e $hist_basedir ]] && mkdir -p $hist_basedir
+        touch $HIST_FILE
+    fi
+}
+
+get_ssh_pid() {
+    SSH_CLIENT_PID=$( lsof -n -iTCP -sTCP:ESTABLISHED | awk '$1=="ssh"{ print $2 }' )
+}
+
+get_curr_conn() {
+    local ps_list ssh_client_cmd
+    if [[ -n $SSH_CLIENT_PID ]]; then
+        ps_list=$( ps -eo pid,args | grep '[s]sh' )
+        for pid in $SSH_CLIENT_PID; do
+            ssh_client_cmd="$( echo "$ps_list" \
+                                | awk -v pid=$pid '$1==pid{$1=""; sub(/^ /,""); print $0; exit}' )"
+            if [[ $ssh_client_cmd =~ ${EXCLUDE_RE:-^$} ]]; then
+                continue
+            else
+                CONN_ARR[ ${i:=0} ]="$ssh_client_cmd"
+                i=$(( $i + 1 ))
+            fi
+        done
+    fi
+}
+
+check_conn() {
+    # Exit if no current or history connections available.
+    if [[ -z $CONN_ARR ]] && [[ ! -s $HIST_FILE ]]; then
+        echo "No current ssh connections and $HIST_FILE is empty." >&2
+        exit 1
+    fi
+}
+
+get_hist_conn() {
+    if [[ -s $HIST_FILE ]]; then
+        # Fill the history array.
+        while read line; do
+            HIST_ARR[ ${j:=0} ]="$line"
+            j=$(( $j + 1 ))
+        done < $HIST_FILE
+    fi
+}
+
+eliminate_dups() {
+    # Eliminate duplicate items in connection array.
+    # Here the array expansion via wildcard is necessary.
+    IFS=$'\n' CONN_ARR=( $( echo "${CONN_ARR[*]}" | sort -u ) )
+    unset IFS
+}
+
+check_auto_flag() {
+    if [[ ${#CONN_ARR[@]} -eq 1 ]] && $AUTO_FLAG; then
+        INDEX=1
+    fi 
+}
+
+print_curr_conn() {
+    check_auto_flag
+    for x in ${!CONN_ARR[@]}; do
+        [[ -z $INDEX ]] && printf "[%02d] %s\n" $(( $x + 1 )) "${CONN_ARR[ $x ]}"
         if [[ -s $HIST_FILE ]]; then 
             # Check if the current connection is already in
             # the history array and if so reset this item.
-            for y in "${!hist_arr[@]}"; do
-                if [[ ${hist_arr[ $y ]} =~ ^${conn_arr[ $x ]}$ ]]; then
-                    hist_arr[ $y ]=""
+            for y in "${!HIST_ARR[@]}"; do
+                if [[ ${HIST_ARR[ $y ]} =~ ^${CONN_ARR[ $x ]}$ ]]; then
+                    HIST_ARR[ $y ]=""
                 fi
             done
         fi
     done
+}
 
-    # Cleanup history array.
-    for i in "${!hist_arr[@]}"; do
+cleanup_hist() {
+    [[ -z $CONN_ARR ]] && return
+    local hist_arr_clean
+    for i in "${!HIST_ARR[@]}"; do
         # Fill the array without empty items.
-        [[ -n ${hist_arr[ $i ]} ]] && hist_arr_clean=( "${hist_arr_clean[@]}" "${hist_arr[ $i ]}" )
+        if [[ -n ${HIST_ARR[ $i ]} ]]; then
+            hist_arr_clean[ ${x:=0} ]="${HIST_ARR[ $i ]}"
+            x=$(( $x + 1 ))
+        fi
     done
-    hist_arr=( "${hist_arr_clean[@]}" )
-fi
+    HIST_ARR=( "${hist_arr_clean[@]}" )
+}
 
-# Print history connections. 
-if [[ -n $hist_arr ]] && [[ -z $INDEX ]]; then
+print_hist_conn() {
+    check_auto_flag
+    if [[ -z $HIST_ARR ]] || [[ -n $INDEX ]]; then
+        return
+    fi
     echo '[--]'
-    for i in "${!hist_arr[@]}"; do
-        printf "[%02d] %s\n" $(( ${#conn_arr[@]} + $i + 1 )) "${hist_arr[ $i ]}"
+    for i in "${!HIST_ARR[@]}"; do
+        printf "[%02d] %s\n" $(( ${#CONN_ARR[@]} + $i + 1 )) "${HIST_ARR[ $i ]}"
     done
-fi
+}
 
-# Check if there was an index passed directly or we have to read it.
-if [[ -n $INDEX ]]; then
-    input="$INDEX"
-else
-    echo -n '>id: '
-    read input
-fi
+read_input() {
+    $LIST_FLAG && exit
+    # Check if there was an index passed directly or we have to read it.
+    if [[ -n $INDEX ]]; then
+        INPUT="$INDEX"
+    else
+        echo -n '>id: '
+        read INPUT
+    fi
+}
 
-# Validate input.
-if [[ ! $input =~ ^([0-9]{1,3}){0,1}([+-][0-9]{1,3}){0,1}$ ]]; then
-    echo "Only int or int+int (max. 3 digits each) allowed." >&2
-    exit 1
-else
-    # Remove all leading zeros, example input: "04+01".
-    input=$( echo $input | sed 's/^0*//; s/+0*/+/; s/-0*/-/' )
-    # Split off conn_id and subtract 1 since array index starts with 0.
-    conn_id=${input%[+-]*}
+validate_input() {
+    if [[ ! $INPUT =~ $VALIDATION_PATTERN ]]; then
+        echo "Invalid input." >&2
+        usage
+        exit 1
+    fi
+}
+
+build_ssh_cmd() {
+    local conn_id add_val ssh_client_cmd ip_addr last_oct new_last_oct new_ip_addr
+    # Remove all leading zeros, example INPUT: "04+01".
+    INPUT=$( echo $INPUT | sed 's/^0*//; s/+0*/+/; s/-0*/-/' )
+    # Split off connection id and subtract 1 since array index starts with 0.
+    conn_id=${INPUT%[+-]*}
     if [[ -n $conn_id ]] && [[ $conn_id -ne 0 ]]; then
         conn_id=$(( $conn_id - 1 ))
     fi
     # Check if arithm. operator given.
-    if [[ $input =~ [+-] ]]; then
-        add_val=${input#*[+-]}
-        [[ $input =~ - ]] && add_val="-$add_val"
+    if [[ $INPUT =~ [+-] ]]; then
+        add_val=${INPUT#*[+-]}
+        [[ $INPUT =~ - ]] && add_val="-$add_val"
     fi
 
-    # Select the ssh command to execute.
+    # Select the ssh command to be executed.
     # Distinguish to which array the id belongs.
     # Use id 0 if connection id is unset.
-    if [[ -n $conn_arr ]] && [[ $conn_id -lt $(( ${#conn_arr[@]} )) ]]; then
-        ssh_client_cmd="${conn_arr[ ${conn_id:-0} ]}"
+    if [[ -n $CONN_ARR ]] && [[ $conn_id -lt ${#CONN_ARR[@]} ]]; then
+        ssh_client_cmd="${CONN_ARR[ ${conn_id:-0} ]}"
     # Check if id is in range.
-    elif [[ $(( $conn_id + 1 )) -gt $(( ${#conn_arr[@]} + ${#hist_arr[@]} )) ]]; then
+    elif [[ $(( $conn_id + 1 )) -gt $(( ${#CONN_ARR[@]} + ${#HIST_ARR[@]} )) ]]; then
         echo "The id is out of range." >&2
         exit 1
     else
         # If there is no current connection or the id is out of
         # range of the connection array use the history array.
-        conn_id=$(( $conn_id - ${#conn_arr[@]} ))
-        ssh_client_cmd="${hist_arr[ ${conn_id:-0} ]}"
+        conn_id=$(( $conn_id - ${#CONN_ARR[@]} ))
+        ssh_client_cmd="${HIST_ARR[ ${conn_id:-0} ]}"
     fi
 
     if [[ -n $add_val ]]; then
@@ -153,18 +242,41 @@ else
             exit 1
         fi
         # To stay MacOS compatible avoid the use of sed's "-r" parameter.
-        ssh_login="$( echo "$ssh_client_cmd" \
+        SSH_LOGIN="$( echo "$ssh_client_cmd" \
                         | sed "s/[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*/$new_ip_addr/" )"
     else
-        ssh_login="$ssh_client_cmd"
+        SSH_LOGIN="$ssh_client_cmd"
     fi
+}
 
-    # Write history file.
-    {   for line in "${conn_arr[@]}" "${hist_arr[@]}"; do
-            echo "$line"
+write_hist() {
+    {   echo $SSH_LOGIN;
+        for line in "${CONN_ARR[@]}" "${HIST_ARR[@]}"; do
+            [[ ! $line =~ ^$SSH_LOGIN$ ]] && echo "$line"
         done 
-    }   | head -n "${MAX_HIST_LINES:-0}" > $HIST_FILE
+    } | head -n "${MAX_HIST_LINES:-0}" > $HIST_FILE
+}
 
-    # Do the login.
-    $ssh_login
-fi
+do_ssh_login() {
+    $SSH_LOGIN
+}
+
+#------
+# MAIN
+#------
+
+parse_argv
+create_hist_file
+get_ssh_pid
+get_curr_conn
+check_conn
+get_hist_conn
+eliminate_dups
+print_curr_conn
+cleanup_hist
+print_hist_conn
+read_input
+validate_input
+build_ssh_cmd
+write_hist
+do_ssh_login
